### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by OSRSEdenGuard** [OddDrifter/region-names-patcher#2]
When I run the Synth patcher I get thrown this log:

```
Running(""): "dotnet" "run --project \"C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher\Patcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Modding\Skyrim AE\NVGO fork\Stock Game\Data\" --ExtraDataFolder \"C:\Modding\Skyrim AE\NVGO fork\tools\Synthesis Updated\Data\Skyrim Special Edition\region-names-patcher\" --FormIDRangeMode Auto --GameRelease SkyrimSE --InternalDataFolder C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher\InternalData --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\1 - region-names-patcher\Synthesis.esp\" --PatcherName region-names-patcher --SourcePath \"C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\1 - SynFixBOOKRecordTypes\Synthesis.esp\""
Mutagen version: 0.46
Mutagen sha: 
Synthesis version: 0.30.2
Synthesis sha: b4141a4e535a46785d946c43203afe7bb955f1cf
Newtonsoft version: 13.0.3
run-patcher --DataFolderPath "C:\Modding\Skyrim AE\NVGO fork\Stock Game\Data" --ExtraDataFolder "C:\Modding\Skyrim AE\NVGO fork\tools\Synthesis Updated\Data\Skyrim Special Edition\region-names-patcher" --FormIDRangeMode Auto --GameRelease SkyrimSE --InternalDataFolder C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher\InternalData --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\1 - region-names-patcher\Synthesis.esp" --PatcherName region-names-patcher --SourcePath "C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\1 - SynFixBOOKRecordTypes\Synthesis.esp"
Checking runnability
Checking runnability complete
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
Finished patch.
Writing to output: C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Workspace\Synthesis\1 - region-names-patcher\Synthesis.esp
Unhandled exception. Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher\InternalData\Regions\AudioExtDLC2Ashlands - 0195C3_Dragonborn.esm.json
 ---> System.ArgumentException: Could not parse string into P2Float: -8091.461, 5481.3125
   at Mutagen.Bethesda.Serialization.Newtonsoft.NewtonsoftJsonSerializationReaderKernel.ReadP2Float(JsonReadingUnit reader)
   at Mutagen.Bethesda.Skyrim.RegionArea_Serialization.DeserializeSingleFieldInto[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, IRegionArea obj, SerializationMetaData metaData, String name) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\RegionArea_Serializations.g.cs:line 106
   at Mutagen.Bethesda.Skyrim.RegionArea_Serialization.DeserializeInto[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, IRegionArea obj, SerializationMetaData metaData) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\RegionArea_Serializations.g.cs:line 127
   at Mutagen.Bethesda.Skyrim.RegionArea_Serialization.Deserialize[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, SerializationMetaData metaData) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\RegionArea_Serializations.g.cs:line 79
   at Mutagen.Bethesda.Serialization.Newtonsoft.NewtonsoftJsonSerializationReaderKernel.ReadLoqui[TObject](JsonReadingUnit reader, SerializationMetaData serializationMetaData, ReadAsync`3 readCall)
   at Mutagen.Bethesda.Skyrim.Region_Serialization.DeserializeSingleFieldInto[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, IRegion obj, SerializationMetaData metaData, String name) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\Region_Serializations.g.cs:line 148
   at Mutagen.Bethesda.Skyrim.Region_Serialization.DeserializeInto[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, IRegion obj, SerializationMetaData metaData) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\Region_Serializations.g.cs:line 190
   at Mutagen.Bethesda.Skyrim.Region_Serialization.Deserialize[TReadObject](TReadObject reader, ISerializationReaderKernel`1 kernel, SerializationMetaData metaData) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\Region_Serializations.g.cs:line 119
   at Mutagen.Bethesda.Serialization.Newtonsoft.NewtonsoftJsonSerializationReaderKernel.ReadLoqui[TObject](JsonReadingUnit reader, SerializationMetaData serializationMetaData, ReadAsync`3 readCall)
   at Mutagen.Bethesda.Skyrim.SkyrimMod_Serialization.<>c__5`2.<<DeserializeInto>b__5_103>d.MoveNext() in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\SkyrimMod_Serializations.g.cs:line 1852
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.<>c__DisplayClass19_0`4.<<ReadFilePerRecord>b__4>d.MoveNext()
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Serialization.Newtonsoft.MutagenJsonConverterSkyrimModMixIns.DeserializeInternal[TMeta](MutagenJsonConverter converterBootstrap, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, ReadInto`3 metaReader, Nullable`1 cancel) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenJsonConverter_SkyrimMod_MixIns.g.cs:line 123
   at Mutagen.Bethesda.Serialization.Newtonsoft.MutagenJsonConverterSkyrimModMixIns.Deserialize(MutagenJsonConverter converterBootstrap, DirectoryPath path, Object extraMeta, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, Nullable`1 cancel) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenJsonConverter_SkyrimMod_MixIns.g.cs:line 137
   at Patcher.Serialization.Helper.DeserializeFromPath(DirectoryPath path) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher.Serialization\Helper.cs:line 13
   at Patcher.Program.Func(IPatcherState`2 state) in C:\Users\A4-H2O\AppData\Local\Temp\Synthesis\mnz5q5ws.cur\Git\0wijqd12.iul\Runner\Patcher\Program.cs:line 33
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by OddDrifter** [comment]
This should maybe be reported at the [mutagen discord](https://discord.gg/WvTguhhU).

**Comment by Noggog** [comment]
Hah!  Awesome to see you using it like this @OddDrifter 

@OSRSEdenGuard Might be a localization issue, potentially.  What windows language are you using?  And what do your decimal numbers typically look like?   `1.234`?   or `1,234`?

**Comment by OSRSEdenGuard** [comment]
> Hah! Awesome to see you using it like this @OddDrifter
> 
> @OSRSEdenGuard Might be a localization issue, potentially. What windows language are you using? And what do your decimal numbers typically look like? `1.234`? or `1,234`?

Windows using English language. Decimals using `1,234` for native windows apps (like calculator), but shows up as `1.234` in the Synthesis UI

**Comment by Noggog** [comment]
I pushed up some changes to make P2Float parsing to be more standardized and hopefully fix this issue.

@OddDrifter will need to upgrade the patcher to reference the newer Mutagen.Bethesda.Serialization libs, though, as Synthesis won't be able to upgrade that one automatically

**Comment by OddDrifter** [comment]
@OSRSEdenGuard I updated the patcher libraries yesterday. Let me know if it helps.

**Comment by OSRSEdenGuard** [comment]
@OddDrifter Seems to have fixed it! Works now - and thanks a lot :)
